/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        
        // This is to remove unnecessary warnings from your console
        System.setProperty("java.util.logging.config.file", "logging.properties");
        
        TestCases tests = new TestCases(); // Initialize your test class
        HyperlinksCount linksCount = new HyperlinksCount();
        //TODO: call your test case functions one after other here

        tests.testCase01();
        linksCount.testCase01();
        //END Tests


        tests.endTest(); // End your test by clearning connections and closing browser
        linksCount.endTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
